import { motion } from "framer-motion";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import { ArrowRight, Brain, Clock, FileText, Lightbulb, Lock, Microscope, Rocket, Shield, Zap } from "lucide-react";

const ideas = [
  { id: 101, status: "demo", category: "Fleet Intelligence", icon: Zap, color: "text-cyan-400", bg: "from-cyan-500/20 to-cyan-500/5 border-cyan-500/20", title: "SolarEye", tagline: "The Road as a Sensor", description: "Distributed, solar-powered intelligence network that turns passive vehicle assets into active road data nodes.", tags: ["Fleet", "Edge AI", "Starlink", "AIP"], date: "April 2026", href: "/ideas/solareye" },
  { id: 102, status: "demo", category: "AgriTech", icon: Rocket, color: "text-green-400", bg: "from-green-500/20 to-green-500/5 border-green-500/20", title: "PoleHive", tagline: "The Future of Beekeeping", description: "Next-generation smart beehive with modular architecture, non-invasive extraction, and 24/7 solar autonomy.", tags: ["AgriTech", "IoT", "Automation", "Sustainability"], date: "April 2026", href: "/ideas/polehive" },
  { id: 1, status: "concept", category: "AI Infrastructure", icon: Brain, color: "text-purple-400", bg: "from-purple-500/20 to-purple-500/5 border-purple-500/20", title: "AIP Marketplace", tagline: "Let AI agents discover and transact autonomously", description: "A decentralized marketplace where AI agents can browse, negotiate, and purchase services with human-in-the-loop approval gates.", tags: ["A2A Protocol", "Autonomous Agents", "Marketplace", "Vertex AI"], date: "April 2026" },
  { id: 2, status: "demo", category: "AgriTech", icon: Microscope, color: "text-green-400", bg: "from-green-500/20 to-green-500/5 border-green-500/20", title: "Yield Predictor AI", tagline: "Predict harvest yields 90 days in advance", description: "Machine learning model trained on soil composition, weather patterns, and historical yield data to give farmers a 90-day forecast.", tags: ["Machine Learning", "AgriTech", "Forecasting", "Farm"], date: "March 2026" },
  { id: 3, status: "concept", category: "SaaS", icon: Zap, color: "text-yellow-400", bg: "from-yellow-500/20 to-yellow-500/5 border-yellow-500/20", title: "Trackit Intelligence", tagline: "KPIs that explain themselves", description: "An AI layer on top of Trackit that automatically generates plain-English explanations of why numbers changed and suggests actions.", tags: ["Analytics", "AI Explanation", "Trackit", "NLP"], date: "April 2026" },
  { id: 4, status: "patent-pending", category: "AI Safety", icon: Shield, color: "text-blue-400", bg: "from-blue-500/20 to-blue-500/5 border-blue-500/20", title: "Human-in-the-Loop Gate", tagline: "A protocol for safe AI-to-AI transactions", description: "A standardized protocol layer that intercepts AI-to-AI transactions above a defined risk threshold and routes them through approval.", tags: ["AI Safety", "Protocol", "Human Oversight", "AIP"], date: "February 2026" },
  { id: 5, status: "concept", category: "AgriTech", icon: Rocket, color: "text-orange-400", bg: "from-orange-500/20 to-orange-500/5 border-orange-500/20", title: "FarmOS Integration Layer", tagline: "Connect any farm hardware to RoarAdd Farm", description: "A universal adapter protocol that connects IoT sensors, drones, and irrigation controllers into the RoarAdd Farm platform.", tags: ["IoT", "FarmOS", "Integration", "Hardware"], date: "April 2026" },
  { id: 6, status: "demo", category: "IT Consulting", icon: FileText, color: "text-pink-400", bg: "from-pink-500/20 to-pink-500/5 border-pink-500/20", title: "AI Audit Report Generator", tagline: "Automated IT audit reports in minutes", description: "Feed in system logs and configs to get a formatted board-ready IT audit report with risk ratings and remediation steps generated by AI.", tags: ["IT Audit", "Automation", "Compliance", "Reporting"], date: "March 2026" },
];

const statusConfig: Record<string, { label: string; color: string; icon: React.ElementType }> = {
  concept: { label: "Concept", color: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20", icon: Lightbulb },
  demo: { label: "Demo Ready", color: "bg-green-500/10 text-green-400 border-green-500/20", icon: Rocket },
  "patent-pending": { label: "Patent Pending", color: "bg-blue-500/10 text-blue-400 border-blue-500/20", icon: Lock },
};

export default function Ideas() {
  return (
    <div className="relative min-h-screen bg-background overflow-hidden">
      <div className="fixed inset-0 bg-grid-pattern opacity-10 pointer-events-none" />
      <main className="pt-16">
        <section className="py-20 sm:py-24">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 text-center">
            <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>
              <Badge variant="outline" className="mb-6 py-1.5 px-4 bg-yellow-500/10 border-yellow-500/20 text-yellow-400 uppercase tracking-widest text-xs">Ideas Lab</Badge>
              <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold mb-6 leading-tight">Concepts, Demos &<br /><span className="text-gradient">Innovations</span></h1>
              <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">A living showcase of RoarAdd ideas in development — from early concepts to demo-ready prototypes and patent-pending innovations.</p>
            </motion.div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="mt-10 flex flex-wrap justify-center gap-4">
              {Object.entries(statusConfig).map(([key, val]) => (
                <div key={key} className={`flex items-center gap-2 px-4 py-2 rounded-full border text-sm font-medium ${val.color}`}>
                  <val.icon className="w-4 h-4" />{val.label}
                </div>
              ))}
            </motion.div>
          </div>
        </section>
        <section className="pb-24">
          <div className="max-w-7xl mx-auto px-4 sm:px-6">
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {ideas.map((idea, i) => {
                const status = statusConfig[idea.status];
                const CardWrapper = idea.href ? Link : 'div';
                return (
                  <motion.div key={idea.id} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: i * 0.07 }}>
                    <CardWrapper href={idea.href || '#'}>
                      <Card className={`glass-panel h-full hover:border-white/20 transition-all group ${idea.href ? 'cursor-pointer' : ''}`}>
                        <CardHeader>
                          <div className="flex items-start justify-between mb-3">
                            <div className={`w-12 h-12 rounded-2xl bg-gradient-to-br ${idea.bg} border flex items-center justify-center group-hover:scale-110 transition-transform`}>
                              <idea.icon className={`w-6 h-6 ${idea.color}`} />
                            </div>
                            <div className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full border text-xs font-medium ${status.color}`}>
                              <status.icon className="w-3 h-3" />{status.label}
                            </div>
                          </div>
                          <Badge variant="secondary" className="w-fit text-xs mb-2">{idea.category}</Badge>
                          <CardTitle className="text-xl">{idea.title}</CardTitle>
                          <p className={`text-sm font-medium ${idea.color} mb-1`}>{idea.tagline}</p>
                          <CardDescription className="leading-relaxed">{idea.description}</CardDescription>
                        </CardHeader>
                        <CardContent>
                          <div className="flex flex-wrap gap-2 mb-4">
                            {idea.tags.map(tag => <Badge key={tag} variant="secondary" className="text-xs">{tag}</Badge>)}
                          </div>
                          <div className="flex items-center justify-between text-xs text-muted-foreground">
                            <div className="flex items-center gap-1"><Clock className="w-3 h-3" />{idea.date}</div>
                            {idea.href ? (
                              <div className="flex items-center gap-1 text-primary group-hover:underline">Explore <ArrowRight className="w-3 h-3" /></div>
                            ) : (
                              <span>RoarAdd LLC</span>
                            )}
                          </div>
                        </CardContent>
                      </Card>
                    </CardWrapper>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
